window.WORD_PACKS = [
  { id: "starter", name: "高频核心", subtitle: "先拿基础分", maxIndex: 72, source: "内置中考高频样例，待替换为核验来源" },
  { id: "middle", name: "中频扩展", subtitle: "补阅读和写作", maxIndex: 156, source: "内置中考高频样例，待替换为核验来源" },
  { id: "full-sample", name: "样例全量", subtitle: "当前 234 词冲刺", maxIndex: 9999, source: "非官方完整词库，仅作结构与学习流程样例" }
];

window.WORDS = [
  { word: "ability", phonetic: "/əˈbɪləti/", meaning: "能力", example: "Practice improves your ability.", level: "核心名词" },
  { word: "able", phonetic: "/ˈeɪbl/", meaning: "能够的", example: "I am able to remember this word.", level: "核心形容词" },
  { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "在国外", example: "She wants to study abroad.", level: "高频副词" },
  { word: "accept", phonetic: "/əkˈsept/", meaning: "接受", example: "Accept mistakes and learn from them.", level: "核心动词" },
  { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "实现；达到", example: "You can achieve your goal.", level: "核心动词" },
  { word: "activity", phonetic: "/ækˈtɪvəti/", meaning: "活动", example: "School activities are useful.", level: "校园词" },
  { word: "advice", phonetic: "/ədˈvaɪs/", meaning: "建议", example: "My teacher gave me advice.", level: "核心名词" },
  { word: "afford", phonetic: "/əˈfɔːd/", meaning: "负担得起", example: "We cannot afford to waste time.", level: "核心动词" },
  { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "虽然", example: "Although it is hard, I keep going.", level: "高频连词" },
  { word: "ancient", phonetic: "/ˈeɪnʃənt/", meaning: "古代的", example: "China has an ancient history.", level: "阅读词" },
  { word: "appear", phonetic: "/əˈpɪə/", meaning: "出现", example: "This word often appears in tests.", level: "核心动词" },
  { word: "arrive", phonetic: "/əˈraɪv/", meaning: "到达", example: "We arrive at school early.", level: "核心动词" },
  { word: "attention", phonetic: "/əˈtenʃn/", meaning: "注意力", example: "Pay attention to spelling.", level: "学习词" },
  { word: "available", phonetic: "/əˈveɪləbl/", meaning: "可获得的", example: "The book is available online.", level: "阅读词" },
  { word: "avoid", phonetic: "/əˈvɔɪd/", meaning: "避免", example: "Avoid making the same mistake.", level: "核心动词" },
  { word: "believe", phonetic: "/bɪˈliːv/", meaning: "相信", example: "Believe in yourself.", level: "核心动词" },
  { word: "borrow", phonetic: "/ˈbɒrəʊ/", meaning: "借入", example: "May I borrow your dictionary?", level: "生活词" },
  { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning: "挑战", example: "The exam is a challenge.", level: "情绪词" },
  { word: "change", phonetic: "/tʃeɪndʒ/", meaning: "改变", example: "Small habits change scores.", level: "核心词" },
  { word: "choice", phonetic: "/tʃɔɪs/", meaning: "选择", example: "Make a wise choice.", level: "核心名词" },
  { word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "交流", example: "English helps us communicate.", level: "话题词" },
  { word: "compare", phonetic: "/kəmˈpeə/", meaning: "比较", example: "Compare the two answers.", level: "阅读词" },
  { word: "complete", phonetic: "/kəmˈpliːt/", meaning: "完成", example: "Complete today's task first.", level: "核心动词" },
  { word: "condition", phonetic: "/kənˈdɪʃn/", meaning: "条件；状况", example: "Sleep affects your condition.", level: "阅读词" },
  { word: "confidence", phonetic: "/ˈkɒnfɪdəns/", meaning: "信心", example: "Correct answers build confidence.", level: "抽象名词" },
  { word: "continue", phonetic: "/kənˈtɪnjuː/", meaning: "继续", example: "Continue reviewing every day.", level: "核心动词" },
  { word: "control", phonetic: "/kənˈtrəʊl/", meaning: "控制", example: "Control your study time.", level: "核心词" },
  { word: "culture", phonetic: "/ˈkʌltʃə/", meaning: "文化", example: "Language carries culture.", level: "话题词" },
  { word: "decision", phonetic: "/dɪˈsɪʒn/", meaning: "决定", example: "A plan is a good decision.", level: "抽象名词" },
  { word: "describe", phonetic: "/dɪˈskraɪb/", meaning: "描述", example: "Describe the picture in English.", level: "核心动词" },
  { word: "develop", phonetic: "/dɪˈveləp/", meaning: "发展；养成", example: "Develop a review habit.", level: "核心动词" },
  { word: "different", phonetic: "/ˈdɪfrənt/", meaning: "不同的", example: "Different words need different review.", level: "核心形容词" },
  { word: "difficulty", phonetic: "/ˈdɪfɪkəlti/", meaning: "困难", example: "We can solve this difficulty.", level: "抽象名词" },
  { word: "discover", phonetic: "/dɪˈskʌvə/", meaning: "发现", example: "Discover your weak words.", level: "核心动词" },
  { word: "education", phonetic: "/ˌedʒuˈkeɪʃn/", meaning: "教育", example: "Education changes lives.", level: "话题词" },
  { word: "effort", phonetic: "/ˈefət/", meaning: "努力", example: "Your effort will pay off.", level: "抽象名词" },
  { word: "encourage", phonetic: "/ɪnˈkʌrɪdʒ/", meaning: "鼓励", example: "Teachers encourage students.", level: "核心动词" },
  { word: "energy", phonetic: "/ˈenədʒi/", meaning: "精力；能源", example: "Save energy for review.", level: "话题词" },
  { word: "environment", phonetic: "/ɪnˈvaɪrənmənt/", meaning: "环境", example: "Protect the environment.", level: "话题词" },
  { word: "especially", phonetic: "/ɪˈspeʃəli/", meaning: "尤其", example: "Review spelling especially carefully.", level: "高频副词" },
  { word: "experience", phonetic: "/ɪkˈspɪəriəns/", meaning: "经历；经验", example: "This is a useful experience.", level: "核心名词" },
  { word: "explain", phonetic: "/ɪkˈspleɪn/", meaning: "解释", example: "Explain the meaning clearly.", level: "核心动词" },
  { word: "famous", phonetic: "/ˈfeɪməs/", meaning: "著名的", example: "Shenzhen is a famous city.", level: "核心形容词" },
  { word: "favorite", phonetic: "/ˈfeɪvərɪt/", meaning: "最喜欢的", example: "English is my favorite subject.", level: "生活词" },
  { word: "finally", phonetic: "/ˈfaɪnəli/", meaning: "最后", example: "Finally, check your answers.", level: "高频副词" },
  { word: "foreign", phonetic: "/ˈfɒrən/", meaning: "外国的", example: "Learning a foreign language takes time.", level: "话题词" },
  { word: "grammar", phonetic: "/ˈɡræmə/", meaning: "语法", example: "Vocabulary helps grammar.", level: "学习词" },
  { word: "habit", phonetic: "/ˈhæbɪt/", meaning: "习惯", example: "A good habit starts today.", level: "生活词" },
  { word: "healthy", phonetic: "/ˈhelθi/", meaning: "健康的", example: "Stay healthy before the exam.", level: "生活词" },
  { word: "however", phonetic: "/haʊˈevə/", meaning: "然而", example: "It is hard; however, I can do it.", level: "高频连词" },
  { word: "imagine", phonetic: "/ɪˈmædʒɪn/", meaning: "想象", example: "Imagine the word in a sentence.", level: "核心动词" },
  { word: "important", phonetic: "/ɪmˈpɔːtnt/", meaning: "重要的", example: "Review is important.", level: "核心形容词" },
  { word: "improve", phonetic: "/ɪmˈpruːv/", meaning: "提高；改善", example: "Review improves memory.", level: "核心动词" },
  { word: "include", phonetic: "/ɪnˈkluːd/", meaning: "包括", example: "The list includes key words.", level: "核心动词" },
  { word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "影响", example: "Words influence reading scores.", level: "阅读词" },
  { word: "instead", phonetic: "/ɪnˈsted/", meaning: "代替；反而", example: "Review instead of guessing.", level: "高频副词" },
  { word: "interest", phonetic: "/ˈɪntrəst/", meaning: "兴趣", example: "Games raise interest.", level: "抽象名词" },
  { word: "knowledge", phonetic: "/ˈnɒlɪdʒ/", meaning: "知识", example: "Words are basic knowledge.", level: "抽象名词" },
  { word: "language", phonetic: "/ˈlæŋɡwɪdʒ/", meaning: "语言", example: "English is a useful language.", level: "话题词" },
  { word: "necessary", phonetic: "/ˈnesəsəri/", meaning: "必要的", example: "Review is necessary.", level: "核心形容词" },
  { word: "notice", phonetic: "/ˈnəʊtɪs/", meaning: "注意到；通知", example: "Notice the spelling change.", level: "核心词" },
  { word: "opinion", phonetic: "/əˈpɪnjən/", meaning: "观点", example: "Give your opinion in writing.", level: "写作词" },
  { word: "opportunity", phonetic: "/ˌɒpəˈtjuːnəti/", meaning: "机会", example: "Every review is an opportunity.", level: "阅读词" },
  { word: "patient", phonetic: "/ˈpeɪʃnt/", meaning: "耐心的；病人", example: "Be patient with yourself.", level: "核心词" },
  { word: "popular", phonetic: "/ˈpɒpjələ/", meaning: "受欢迎的", example: "This app is popular.", level: "核心形容词" },
  { word: "practice", phonetic: "/ˈpræktɪs/", meaning: "练习", example: "Practice every morning.", level: "学习词" },
  { word: "prepare", phonetic: "/prɪˈpeə/", meaning: "准备", example: "Prepare for the exam.", level: "核心动词" },
  { word: "progress", phonetic: "/ˈprəʊɡres/", meaning: "进步；进展", example: "Your progress is visible.", level: "学习词" },
  { word: "protect", phonetic: "/prəˈtekt/", meaning: "保护", example: "Protect your study time.", level: "核心动词" },
  { word: "purpose", phonetic: "/ˈpɜːpəs/", meaning: "目的", example: "Know the purpose of review.", level: "抽象名词" },
  { word: "realize", phonetic: "/ˈriːəlaɪz/", meaning: "意识到；实现", example: "I realize review matters.", level: "核心动词" },
  { word: "reason", phonetic: "/ˈriːzn/", meaning: "原因", example: "Find the reason for mistakes.", level: "核心名词" },
  { word: "receive", phonetic: "/rɪˈsiːv/", meaning: "收到", example: "Receive feedback quickly.", level: "核心动词" },
  { word: "remember", phonetic: "/rɪˈmembə/", meaning: "记住", example: "Remember words by examples.", level: "学习词" },
  { word: "review", phonetic: "/rɪˈvjuː/", meaning: "复习", example: "Review before forgetting.", level: "学习词" },
  { word: "sentence", phonetic: "/ˈsentəns/", meaning: "句子", example: "Make a sentence with it.", level: "学习词" },
  { word: "serious", phonetic: "/ˈsɪəriəs/", meaning: "严肃的；严重的", example: "Take spelling seriously.", level: "核心形容词" },
  { word: "similar", phonetic: "/ˈsɪmələ/", meaning: "相似的", example: "These two words are similar.", level: "阅读词" },
  { word: "situation", phonetic: "/ˌsɪtʃuˈeɪʃn/", meaning: "情况", example: "Understand the situation.", level: "阅读词" },
  { word: "solution", phonetic: "/səˈluːʃn/", meaning: "解决办法", example: "Review is the solution.", level: "抽象名词" },
  { word: "succeed", phonetic: "/səkˈsiːd/", meaning: "成功", example: "You can succeed.", level: "核心动词" },
  { word: "suggest", phonetic: "/səˈdʒest/", meaning: "建议", example: "I suggest daily review.", level: "核心动词" },
  { word: "support", phonetic: "/səˈpɔːt/", meaning: "支持", example: "Parents support learning.", level: "核心词" },
  { word: "through", phonetic: "/θruː/", meaning: "通过；穿过", example: "Learn through examples.", level: "高频介词" },
  { word: "understand", phonetic: "/ˌʌndəˈstænd/", meaning: "理解", example: "Understand before memorizing.", level: "核心动词" },
  { word: "valuable", phonetic: "/ˈvæljuəbl/", meaning: "有价值的", example: "Time is valuable.", level: "核心形容词" },
  { word: "without", phonetic: "/wɪˈðaʊt/", meaning: "没有", example: "Do not guess without review.", level: "高频介词" },
  { word: "accident", phonetic: "/ˈæksɪdənt/", meaning: "事故；意外", example: "Be careful and avoid accidents.", level: "生活词" },
  { word: "address", phonetic: "/əˈdres/", meaning: "地址；演讲", example: "Write your address clearly.", level: "生活词" },
  { word: "advantage", phonetic: "/ədˈvɑːntɪdʒ/", meaning: "优点；优势", example: "Practice gives you an advantage.", level: "阅读词" },
  { word: "advertisement", phonetic: "/ədˈvɜːtɪsmənt/", meaning: "广告", example: "Read the advertisement carefully.", level: "阅读词" },
  { word: "against", phonetic: "/əˈɡenst/", meaning: "反对；倚着", example: "We played against another class.", level: "高频介词" },
  { word: "agree", phonetic: "/əˈɡriː/", meaning: "同意", example: "I agree with your idea.", level: "核心动词" },
  { word: "allow", phonetic: "/əˈlaʊ/", meaning: "允许", example: "Phones are not allowed in the exam.", level: "核心动词" },
  { word: "almost", phonetic: "/ˈɔːlməʊst/", meaning: "几乎", example: "I almost finished the task.", level: "高频副词" },
  { word: "alone", phonetic: "/əˈləʊn/", meaning: "独自；单独", example: "She studies alone after school.", level: "生活词" },
  { word: "already", phonetic: "/ɔːlˈredi/", meaning: "已经", example: "I have already reviewed it.", level: "高频副词" },
  { word: "amazing", phonetic: "/əˈmeɪzɪŋ/", meaning: "令人惊奇的", example: "Your progress is amazing.", level: "情绪词" },
  { word: "among", phonetic: "/əˈmʌŋ/", meaning: "在……之中", example: "This word is common among tests.", level: "高频介词" },
  { word: "angry", phonetic: "/ˈæŋɡri/", meaning: "生气的", example: "Do not be angry about mistakes.", level: "情绪词" },
  { word: "answer", phonetic: "/ˈɑːnsə/", meaning: "答案；回答", example: "Check your answer twice.", level: "学习词" },
  { word: "anywhere", phonetic: "/ˈeniweə/", meaning: "任何地方", example: "You can review words anywhere.", level: "高频副词" },
  { word: "area", phonetic: "/ˈeəriə/", meaning: "地区；面积", example: "This area is quiet.", level: "阅读词" },
  { word: "article", phonetic: "/ˈɑːtɪkl/", meaning: "文章；物品", example: "Read the article quickly first.", level: "阅读词" },
  { word: "asleep", phonetic: "/əˈsliːp/", meaning: "睡着的", example: "Do not study when you are asleep.", level: "生活词" },
  { word: "belong", phonetic: "/bɪˈlɒŋ/", meaning: "属于", example: "This book belongs to me.", level: "核心动词" },
  { word: "beside", phonetic: "/bɪˈsaɪd/", meaning: "在……旁边", example: "The dictionary is beside me.", level: "高频介词" },
  { word: "besides", phonetic: "/bɪˈsaɪdz/", meaning: "除……之外；而且", example: "Besides English, I like math.", level: "高频副词" },
  { word: "brave", phonetic: "/breɪv/", meaning: "勇敢的", example: "Be brave when you speak English.", level: "品质词" },
  { word: "business", phonetic: "/ˈbɪznəs/", meaning: "商业；事情", example: "His business is successful.", level: "话题词" },
  { word: "careless", phonetic: "/ˈkeələs/", meaning: "粗心的", example: "Careless mistakes cost marks.", level: "学习词" },
  { word: "certain", phonetic: "/ˈsɜːtn/", meaning: "确定的；某个", example: "I am certain about the answer.", level: "核心形容词" },
  { word: "chance", phonetic: "/tʃɑːns/", meaning: "机会", example: "Take every chance to learn.", level: "核心名词" },
  { word: "cheap", phonetic: "/tʃiːp/", meaning: "便宜的", example: "The ticket is cheap.", level: "生活词" },
  { word: "clearly", phonetic: "/ˈklɪəli/", meaning: "清楚地", example: "Write clearly in the exam.", level: "高频副词" },
  { word: "collect", phonetic: "/kəˈlekt/", meaning: "收集", example: "Collect useful phrases.", level: "核心动词" },
  { word: "comfortable", phonetic: "/ˈkʌmftəbl/", meaning: "舒服的", example: "Find a comfortable place to study.", level: "生活词" },
  { word: "common", phonetic: "/ˈkɒmən/", meaning: "普通的；常见的", example: "This is a common word.", level: "核心形容词" },
  { word: "community", phonetic: "/kəˈmjuːnəti/", meaning: "社区", example: "Our community is friendly.", level: "话题词" },
  { word: "competition", phonetic: "/ˌkɒmpəˈtɪʃn/", meaning: "比赛；竞争", example: "The competition starts tomorrow.", level: "校园词" },
  { word: "consider", phonetic: "/kənˈsɪdə/", meaning: "考虑", example: "Consider the best answer.", level: "核心动词" },
  { word: "conversation", phonetic: "/ˌkɒnvəˈseɪʃn/", meaning: "谈话", example: "Make a short conversation.", level: "学习词" },
  { word: "correct", phonetic: "/kəˈrekt/", meaning: "正确的；改正", example: "Correct the wrong sentence.", level: "学习词" },
  { word: "create", phonetic: "/kriˈeɪt/", meaning: "创造", example: "Create your own example.", level: "核心动词" },
  { word: "crowded", phonetic: "/ˈkraʊdɪd/", meaning: "拥挤的", example: "The bus is crowded.", level: "生活词" },
  { word: "dangerous", phonetic: "/ˈdeɪndʒərəs/", meaning: "危险的", example: "It is dangerous to run here.", level: "生活词" },
  { word: "degree", phonetic: "/dɪˈɡriː/", meaning: "程度；度数；学位", example: "The temperature is 30 degrees.", level: "阅读词" },
  { word: "depend", phonetic: "/dɪˈpend/", meaning: "依靠；取决于", example: "Success depends on practice.", level: "核心动词" },
  { word: "difference", phonetic: "/ˈdɪfrəns/", meaning: "差异", example: "Find the difference between them.", level: "核心名词" },
  { word: "direction", phonetic: "/dəˈrekʃn/", meaning: "方向；说明", example: "Read the directions first.", level: "阅读词" },
  { word: "discuss", phonetic: "/dɪˈskʌs/", meaning: "讨论", example: "Discuss the question with classmates.", level: "核心动词" },
  { word: "disease", phonetic: "/dɪˈziːz/", meaning: "疾病", example: "Exercise helps prevent disease.", level: "健康词" },
  { word: "during", phonetic: "/ˈdjʊərɪŋ/", meaning: "在……期间", example: "Review words during breaks.", level: "高频介词" },
  { word: "easily", phonetic: "/ˈiːzəli/", meaning: "容易地", example: "You can forget words easily.", level: "高频副词" },
  { word: "elder", phonetic: "/ˈeldə/", meaning: "年长的", example: "Respect elder people.", level: "生活词" },
  { word: "enough", phonetic: "/ɪˈnʌf/", meaning: "足够的", example: "Get enough sleep.", level: "高频词" },
  { word: "enter", phonetic: "/ˈentə/", meaning: "进入", example: "Enter the room quietly.", level: "核心动词" },
  { word: "excellent", phonetic: "/ˈeksələnt/", meaning: "优秀的", example: "You did an excellent job.", level: "评价词" },
  { word: "except", phonetic: "/ɪkˈsept/", meaning: "除……之外", example: "Everyone came except Tom.", level: "高频介词" },
  { word: "excited", phonetic: "/ɪkˈsaɪtɪd/", meaning: "兴奋的", example: "I feel excited about progress.", level: "情绪词" },
  { word: "exercise", phonetic: "/ˈeksəsaɪz/", meaning: "锻炼；练习", example: "Exercise keeps you healthy.", level: "健康词" },
  { word: "expect", phonetic: "/ɪkˈspekt/", meaning: "期待；预计", example: "I expect to improve.", level: "核心动词" },
  { word: "expensive", phonetic: "/ɪkˈspensɪv/", meaning: "昂贵的", example: "The dictionary is expensive.", level: "生活词" },
  { word: "fail", phonetic: "/feɪl/", meaning: "失败；不及格", example: "Do not fear to fail.", level: "核心动词" },
  { word: "fair", phonetic: "/feə/", meaning: "公平的；集市", example: "The game is fair.", level: "核心形容词" },
  { word: "familiar", phonetic: "/fəˈmɪliə/", meaning: "熟悉的", example: "This word looks familiar.", level: "阅读词" },
  { word: "fantastic", phonetic: "/fænˈtæstɪk/", meaning: "极好的", example: "That is a fantastic idea.", level: "评价词" },
  { word: "fear", phonetic: "/fɪə/", meaning: "害怕；恐惧", example: "Fear makes learning harder.", level: "情绪词" },
  { word: "festival", phonetic: "/ˈfestɪvl/", meaning: "节日", example: "The Spring Festival is important.", level: "文化词" },
  { word: "future", phonetic: "/ˈfjuːtʃə/", meaning: "未来", example: "Work hard for your future.", level: "核心名词" },
  { word: "general", phonetic: "/ˈdʒenrəl/", meaning: "一般的；总体的", example: "Get the general idea first.", level: "阅读词" },
  { word: "government", phonetic: "/ˈɡʌvənmənt/", meaning: "政府", example: "The government built a park.", level: "话题词" },
  { word: "grade", phonetic: "/ɡreɪd/", meaning: "年级；成绩", example: "I want a better grade.", level: "校园词" },
  { word: "guest", phonetic: "/ɡest/", meaning: "客人", example: "Welcome the guest politely.", level: "生活词" },
  { word: "happen", phonetic: "/ˈhæpən/", meaning: "发生", example: "What happened yesterday?", level: "核心动词" },
  { word: "hardly", phonetic: "/ˈhɑːdli/", meaning: "几乎不", example: "I hardly knew this word before.", level: "高频副词" },
  { word: "helpful", phonetic: "/ˈhelpfl/", meaning: "有帮助的", example: "Examples are helpful.", level: "核心形容词" },
  { word: "honest", phonetic: "/ˈɒnɪst/", meaning: "诚实的", example: "Be honest when you choose.", level: "品质词" },
  { word: "hopeful", phonetic: "/ˈhəʊpfl/", meaning: "有希望的", example: "Stay hopeful before the exam.", level: "情绪词" },
  { word: "illness", phonetic: "/ˈɪlnəs/", meaning: "疾病", example: "He missed school because of illness.", level: "健康词" },
  { word: "impossible", phonetic: "/ɪmˈpɒsəbl/", meaning: "不可能的", example: "Nothing is impossible with effort.", level: "核心形容词" },
  { word: "increase", phonetic: "/ɪnˈkriːs/", meaning: "增加", example: "Increase your review time slowly.", level: "核心动词" },
  { word: "independent", phonetic: "/ˌɪndɪˈpendənt/", meaning: "独立的", example: "Become an independent learner.", level: "品质词" },
  { word: "information", phonetic: "/ˌɪnfəˈmeɪʃn/", meaning: "信息", example: "Find key information in the text.", level: "阅读词" },
  { word: "international", phonetic: "/ˌɪntəˈnæʃnəl/", meaning: "国际的", example: "English is an international language.", level: "话题词" },
  { word: "introduce", phonetic: "/ˌɪntrəˈdjuːs/", meaning: "介绍", example: "Introduce yourself in English.", level: "核心动词" },
  { word: "journey", phonetic: "/ˈdʒɜːni/", meaning: "旅行；旅程", example: "Learning is a long journey.", level: "阅读词" },
  { word: "joy", phonetic: "/dʒɔɪ/", meaning: "快乐", example: "Small progress brings joy.", level: "情绪词" },
  { word: "kindness", phonetic: "/ˈkaɪndnəs/", meaning: "善良", example: "Kindness makes people warm.", level: "品质词" },
  { word: "local", phonetic: "/ˈləʊkl/", meaning: "当地的", example: "Visit a local museum.", level: "话题词" },
  { word: "lonely", phonetic: "/ˈləʊnli/", meaning: "孤独的", example: "She felt lonely at first.", level: "情绪词" },
  { word: "manage", phonetic: "/ˈmænɪdʒ/", meaning: "管理；设法做到", example: "Manage your time well.", level: "核心动词" },
  { word: "meaning", phonetic: "/ˈmiːnɪŋ/", meaning: "意思；意义", example: "Guess the meaning from context.", level: "学习词" },
  { word: "medicine", phonetic: "/ˈmedsn/", meaning: "药；医学", example: "Take medicine on time.", level: "健康词" },
  { word: "method", phonetic: "/ˈmeθəd/", meaning: "方法", example: "Find a better method.", level: "学习词" },
  { word: "mistaken", phonetic: "/mɪˈsteɪkən/", meaning: "错误的", example: "I was mistaken about the answer.", level: "学习词" },
  { word: "modern", phonetic: "/ˈmɒdn/", meaning: "现代的", example: "Shenzhen is a modern city.", level: "话题词" },
  { word: "natural", phonetic: "/ˈnætʃrəl/", meaning: "自然的", example: "Use natural English sentences.", level: "核心形容词" },
  { word: "neighbor", phonetic: "/ˈneɪbə/", meaning: "邻居", example: "My neighbor is friendly.", level: "生活词" },
  { word: "nervous", phonetic: "/ˈnɜːvəs/", meaning: "紧张的", example: "Do not be nervous in the exam.", level: "情绪词" },
  { word: "normal", phonetic: "/ˈnɔːml/", meaning: "正常的", example: "It is normal to forget words.", level: "核心形容词" },
  { word: "offer", phonetic: "/ˈɒfə/", meaning: "提供；主动提出", example: "Can you offer some help?", level: "核心动词" },
  { word: "organize", phonetic: "/ˈɔːɡənaɪz/", meaning: "组织", example: "Organize your notes well.", level: "核心动词" },
  { word: "paragraph", phonetic: "/ˈpærəɡrɑːf/", meaning: "段落", example: "Read the first paragraph.", level: "阅读词" },
  { word: "perfect", phonetic: "/ˈpɜːfɪkt/", meaning: "完美的", example: "You do not need to be perfect.", level: "评价词" },
  { word: "period", phonetic: "/ˈpɪəriəd/", meaning: "时期；一节课", example: "This period is important.", level: "校园词" },
  { word: "personal", phonetic: "/ˈpɜːsənl/", meaning: "个人的", example: "Make a personal study plan.", level: "核心形容词" },
  { word: "pleasant", phonetic: "/ˈpleznt/", meaning: "令人愉快的", example: "It was a pleasant trip.", level: "情绪词" },
  { word: "possible", phonetic: "/ˈpɒsəbl/", meaning: "可能的", example: "Everything is possible.", level: "核心形容词" },
  { word: "present", phonetic: "/ˈpreznt/", meaning: "礼物；现在的", example: "This is a present for you.", level: "核心词" },
  { word: "probably", phonetic: "/ˈprɒbəbli/", meaning: "可能；大概", example: "This word will probably appear.", level: "高频副词" },
  { word: "promise", phonetic: "/ˈprɒmɪs/", meaning: "承诺", example: "Keep your promise to study.", level: "核心词" },
  { word: "provide", phonetic: "/prəˈvaɪd/", meaning: "提供", example: "The app provides review tasks.", level: "核心动词" },
  { word: "public", phonetic: "/ˈpʌblɪk/", meaning: "公共的；公众", example: "Keep public places clean.", level: "话题词" },
  { word: "quickly", phonetic: "/ˈkwɪkli/", meaning: "快速地", example: "Review quickly before sleep.", level: "高频副词" },
  { word: "quiet", phonetic: "/ˈkwaɪət/", meaning: "安静的", example: "Find a quiet place.", level: "生活词" },
  { word: "recently", phonetic: "/ˈriːsntli/", meaning: "最近", example: "I recently learned this word.", level: "高频副词" },
  { word: "record", phonetic: "/ˈrekɔːd/", meaning: "记录", example: "Keep a record of mistakes.", level: "学习词" },
  { word: "reduce", phonetic: "/rɪˈdjuːs/", meaning: "减少", example: "Reduce careless mistakes.", level: "核心动词" },
  { word: "relationship", phonetic: "/rɪˈleɪʃnʃɪp/", meaning: "关系", example: "Build a good relationship.", level: "话题词" },
  { word: "reply", phonetic: "/rɪˈplaɪ/", meaning: "回复", example: "Reply to the question.", level: "核心动词" },
  { word: "require", phonetic: "/rɪˈkwaɪə/", meaning: "要求；需要", example: "Success requires practice.", level: "核心动词" },
  { word: "responsible", phonetic: "/rɪˈspɒnsəbl/", meaning: "负责任的", example: "Be responsible for your study.", level: "品质词" },
  { word: "result", phonetic: "/rɪˈzʌlt/", meaning: "结果", example: "Check the result every week.", level: "核心名词" },
  { word: "safe", phonetic: "/seɪf/", meaning: "安全的", example: "Stay safe on the road.", level: "生活词" },
  { word: "science", phonetic: "/ˈsaɪəns/", meaning: "科学", example: "Science is interesting.", level: "校园词" },
  { word: "secret", phonetic: "/ˈsiːkrət/", meaning: "秘密", example: "The secret is daily review.", level: "阅读词" },
  { word: "several", phonetic: "/ˈsevrəl/", meaning: "几个", example: "Review several words now.", level: "高频限定词" },
  { word: "share", phonetic: "/ʃeə/", meaning: "分享", example: "Share your progress with parents.", level: "核心动词" },
  { word: "simple", phonetic: "/ˈsɪmpl/", meaning: "简单的", example: "Use a simple sentence.", level: "核心形容词" },
  { word: "society", phonetic: "/səˈsaɪəti/", meaning: "社会", example: "Everyone lives in society.", level: "话题词" },
  { word: "special", phonetic: "/ˈspeʃl/", meaning: "特别的", example: "This is a special day.", level: "核心形容词" },
  { word: "standard", phonetic: "/ˈstændəd/", meaning: "标准", example: "Follow the standard answer.", level: "学习词" },
  { word: "strange", phonetic: "/streɪndʒ/", meaning: "奇怪的；陌生的", example: "The word looks strange.", level: "阅读词" },
  { word: "success", phonetic: "/səkˈses/", meaning: "成功", example: "Success comes from effort.", level: "抽象名词" },
  { word: "suddenly", phonetic: "/ˈsʌdənli/", meaning: "突然", example: "Suddenly, I remembered it.", level: "高频副词" },
  { word: "surprise", phonetic: "/səˈpraɪz/", meaning: "惊喜；使惊讶", example: "Your progress is a surprise.", level: "情绪词" },
  { word: "technology", phonetic: "/tekˈnɒlədʒi/", meaning: "科技", example: "Technology changes learning.", level: "话题词" },
  { word: "temperature", phonetic: "/ˈtemprətʃə/", meaning: "温度", example: "The temperature is high today.", level: "生活词" },
  { word: "terrible", phonetic: "/ˈterəbl/", meaning: "糟糕的", example: "A terrible mistake teaches me.", level: "评价词" },
  { word: "themselves", phonetic: "/ðəmˈselvz/", meaning: "他们自己", example: "Students should help themselves.", level: "高频代词" },
  { word: "towards", phonetic: "/təˈwɔːdz/", meaning: "朝；向", example: "Move towards your goal.", level: "高频介词" },
  { word: "traffic", phonetic: "/ˈtræfɪk/", meaning: "交通", example: "Traffic is heavy in the morning.", level: "生活词" },
  { word: "training", phonetic: "/ˈtreɪnɪŋ/", meaning: "训练", example: "Daily training improves memory.", level: "学习词" },
  { word: "translate", phonetic: "/trænzˈleɪt/", meaning: "翻译", example: "Translate the sentence first.", level: "学习词" },
  { word: "trouble", phonetic: "/ˈtrʌbl/", meaning: "麻烦；困难", example: "Ask for help when in trouble.", level: "生活词" },
  { word: "university", phonetic: "/ˌjuːnɪˈvɜːsəti/", meaning: "大学", example: "She wants to enter university.", level: "校园词" },
  { word: "usual", phonetic: "/ˈjuːʒuəl/", meaning: "通常的", example: "Do your usual review.", level: "核心形容词" },
  { word: "village", phonetic: "/ˈvɪlɪdʒ/", meaning: "村庄", example: "The village is beautiful.", level: "话题词" },
  { word: "volunteer", phonetic: "/ˌvɒlənˈtɪə/", meaning: "志愿者", example: "I want to be a volunteer.", level: "话题词" },
  { word: "waste", phonetic: "/weɪst/", meaning: "浪费；废物", example: "Do not waste time.", level: "核心词" },
  { word: "whether", phonetic: "/ˈweðə/", meaning: "是否", example: "I wonder whether he knows it.", level: "高频连词" },
  { word: "whole", phonetic: "/həʊl/", meaning: "整个的", example: "Read the whole sentence.", level: "核心形容词" },
  { word: "wonderful", phonetic: "/ˈwʌndəfl/", meaning: "精彩的", example: "You made wonderful progress.", level: "评价词" }
];
