window.WORDS = [
  { word: "ability", phonetic: "/əˈbɪləti/", meaning: "能力", example: "Practice improves your ability.", level: "核心名词" },
  { word: "able", phonetic: "/ˈeɪbl/", meaning: "能够的", example: "I am able to remember this word.", level: "核心形容词" },
  { word: "abroad", phonetic: "/əˈbrɔːd/", meaning: "在国外", example: "She wants to study abroad.", level: "高频副词" },
  { word: "accept", phonetic: "/əkˈsept/", meaning: "接受", example: "Accept mistakes and learn from them.", level: "核心动词" },
  { word: "achieve", phonetic: "/əˈtʃiːv/", meaning: "实现；达到", example: "You can achieve your goal.", level: "核心动词" },
  { word: "activity", phonetic: "/ækˈtɪvəti/", meaning: "活动", example: "School activities are useful.", level: "校园词" },
  { word: "advice", phonetic: "/ədˈvaɪs/", meaning: "建议", example: "My teacher gave me advice.", level: "核心名词" },
  { word: "afford", phonetic: "/əˈfɔːd/", meaning: "负担得起", example: "We cannot afford to waste time.", level: "核心动词" },
  { word: "although", phonetic: "/ɔːlˈðəʊ/", meaning: "虽然", example: "Although it is hard, I keep going.", level: "高频连词" },
  { word: "ancient", phonetic: "/ˈeɪnʃənt/", meaning: "古代的", example: "China has an ancient history.", level: "阅读词" },
  { word: "appear", phonetic: "/əˈpɪə/", meaning: "出现", example: "This word often appears in tests.", level: "核心动词" },
  { word: "arrive", phonetic: "/əˈraɪv/", meaning: "到达", example: "We arrive at school early.", level: "核心动词" },
  { word: "attention", phonetic: "/əˈtenʃn/", meaning: "注意力", example: "Pay attention to spelling.", level: "学习词" },
  { word: "available", phonetic: "/əˈveɪləbl/", meaning: "可获得的", example: "The book is available online.", level: "阅读词" },
  { word: "avoid", phonetic: "/əˈvɔɪd/", meaning: "避免", example: "Avoid making the same mistake.", level: "核心动词" },
  { word: "believe", phonetic: "/bɪˈliːv/", meaning: "相信", example: "Believe in yourself.", level: "核心动词" },
  { word: "borrow", phonetic: "/ˈbɒrəʊ/", meaning: "借入", example: "May I borrow your dictionary?", level: "生活词" },
  { word: "challenge", phonetic: "/ˈtʃælɪndʒ/", meaning: "挑战", example: "The exam is a challenge.", level: "情绪词" },
  { word: "change", phonetic: "/tʃeɪndʒ/", meaning: "改变", example: "Small habits change scores.", level: "核心词" },
  { word: "choice", phonetic: "/tʃɔɪs/", meaning: "选择", example: "Make a wise choice.", level: "核心名词" },
  { word: "communicate", phonetic: "/kəˈmjuːnɪkeɪt/", meaning: "交流", example: "English helps us communicate.", level: "话题词" },
  { word: "compare", phonetic: "/kəmˈpeə/", meaning: "比较", example: "Compare the two answers.", level: "阅读词" },
  { word: "complete", phonetic: "/kəmˈpliːt/", meaning: "完成", example: "Complete today's task first.", level: "核心动词" },
  { word: "condition", phonetic: "/kənˈdɪʃn/", meaning: "条件；状况", example: "Sleep affects your condition.", level: "阅读词" },
  { word: "confidence", phonetic: "/ˈkɒnfɪdəns/", meaning: "信心", example: "Correct answers build confidence.", level: "抽象名词" },
  { word: "continue", phonetic: "/kənˈtɪnjuː/", meaning: "继续", example: "Continue reviewing every day.", level: "核心动词" },
  { word: "control", phonetic: "/kənˈtrəʊl/", meaning: "控制", example: "Control your study time.", level: "核心词" },
  { word: "culture", phonetic: "/ˈkʌltʃə/", meaning: "文化", example: "Language carries culture.", level: "话题词" },
  { word: "decision", phonetic: "/dɪˈsɪʒn/", meaning: "决定", example: "A plan is a good decision.", level: "抽象名词" },
  { word: "describe", phonetic: "/dɪˈskraɪb/", meaning: "描述", example: "Describe the picture in English.", level: "核心动词" },
  { word: "develop", phonetic: "/dɪˈveləp/", meaning: "发展；养成", example: "Develop a review habit.", level: "核心动词" },
  { word: "different", phonetic: "/ˈdɪfrənt/", meaning: "不同的", example: "Different words need different review.", level: "核心形容词" },
  { word: "difficulty", phonetic: "/ˈdɪfɪkəlti/", meaning: "困难", example: "We can solve this difficulty.", level: "抽象名词" },
  { word: "discover", phonetic: "/dɪˈskʌvə/", meaning: "发现", example: "Discover your weak words.", level: "核心动词" },
  { word: "education", phonetic: "/ˌedʒuˈkeɪʃn/", meaning: "教育", example: "Education changes lives.", level: "话题词" },
  { word: "effort", phonetic: "/ˈefət/", meaning: "努力", example: "Your effort will pay off.", level: "抽象名词" },
  { word: "encourage", phonetic: "/ɪnˈkʌrɪdʒ/", meaning: "鼓励", example: "Teachers encourage students.", level: "核心动词" },
  { word: "energy", phonetic: "/ˈenədʒi/", meaning: "精力；能源", example: "Save energy for review.", level: "话题词" },
  { word: "environment", phonetic: "/ɪnˈvaɪrənmənt/", meaning: "环境", example: "Protect the environment.", level: "话题词" },
  { word: "especially", phonetic: "/ɪˈspeʃəli/", meaning: "尤其", example: "Review spelling especially carefully.", level: "高频副词" },
  { word: "experience", phonetic: "/ɪkˈspɪəriəns/", meaning: "经历；经验", example: "This is a useful experience.", level: "核心名词" },
  { word: "explain", phonetic: "/ɪkˈspleɪn/", meaning: "解释", example: "Explain the meaning clearly.", level: "核心动词" },
  { word: "famous", phonetic: "/ˈfeɪməs/", meaning: "著名的", example: "Shenzhen is a famous city.", level: "核心形容词" },
  { word: "favorite", phonetic: "/ˈfeɪvərɪt/", meaning: "最喜欢的", example: "English is my favorite subject.", level: "生活词" },
  { word: "finally", phonetic: "/ˈfaɪnəli/", meaning: "最后", example: "Finally, check your answers.", level: "高频副词" },
  { word: "foreign", phonetic: "/ˈfɒrən/", meaning: "外国的", example: "Learning a foreign language takes time.", level: "话题词" },
  { word: "grammar", phonetic: "/ˈɡræmə/", meaning: "语法", example: "Vocabulary helps grammar.", level: "学习词" },
  { word: "habit", phonetic: "/ˈhæbɪt/", meaning: "习惯", example: "A good habit starts today.", level: "生活词" },
  { word: "healthy", phonetic: "/ˈhelθi/", meaning: "健康的", example: "Stay healthy before the exam.", level: "生活词" },
  { word: "however", phonetic: "/haʊˈevə/", meaning: "然而", example: "It is hard; however, I can do it.", level: "高频连词" },
  { word: "imagine", phonetic: "/ɪˈmædʒɪn/", meaning: "想象", example: "Imagine the word in a sentence.", level: "核心动词" },
  { word: "important", phonetic: "/ɪmˈpɔːtnt/", meaning: "重要的", example: "Review is important.", level: "核心形容词" },
  { word: "improve", phonetic: "/ɪmˈpruːv/", meaning: "提高；改善", example: "Review improves memory.", level: "核心动词" },
  { word: "include", phonetic: "/ɪnˈkluːd/", meaning: "包括", example: "The list includes key words.", level: "核心动词" },
  { word: "influence", phonetic: "/ˈɪnfluəns/", meaning: "影响", example: "Words influence reading scores.", level: "阅读词" },
  { word: "instead", phonetic: "/ɪnˈsted/", meaning: "代替；反而", example: "Review instead of guessing.", level: "高频副词" },
  { word: "interest", phonetic: "/ˈɪntrəst/", meaning: "兴趣", example: "Games raise interest.", level: "抽象名词" },
  { word: "knowledge", phonetic: "/ˈnɒlɪdʒ/", meaning: "知识", example: "Words are basic knowledge.", level: "抽象名词" },
  { word: "language", phonetic: "/ˈlæŋɡwɪdʒ/", meaning: "语言", example: "English is a useful language.", level: "话题词" },
  { word: "necessary", phonetic: "/ˈnesəsəri/", meaning: "必要的", example: "Review is necessary.", level: "核心形容词" },
  { word: "notice", phonetic: "/ˈnəʊtɪs/", meaning: "注意到；通知", example: "Notice the spelling change.", level: "核心词" },
  { word: "opinion", phonetic: "/əˈpɪnjən/", meaning: "观点", example: "Give your opinion in writing.", level: "写作词" },
  { word: "opportunity", phonetic: "/ˌɒpəˈtjuːnəti/", meaning: "机会", example: "Every review is an opportunity.", level: "阅读词" },
  { word: "patient", phonetic: "/ˈpeɪʃnt/", meaning: "耐心的；病人", example: "Be patient with yourself.", level: "核心词" },
  { word: "popular", phonetic: "/ˈpɒpjələ/", meaning: "受欢迎的", example: "This app is popular.", level: "核心形容词" },
  { word: "practice", phonetic: "/ˈpræktɪs/", meaning: "练习", example: "Practice every morning.", level: "学习词" },
  { word: "prepare", phonetic: "/prɪˈpeə/", meaning: "准备", example: "Prepare for the exam.", level: "核心动词" },
  { word: "progress", phonetic: "/ˈprəʊɡres/", meaning: "进步；进展", example: "Your progress is visible.", level: "学习词" },
  { word: "protect", phonetic: "/prəˈtekt/", meaning: "保护", example: "Protect your study time.", level: "核心动词" },
  { word: "purpose", phonetic: "/ˈpɜːpəs/", meaning: "目的", example: "Know the purpose of review.", level: "抽象名词" },
  { word: "realize", phonetic: "/ˈriːəlaɪz/", meaning: "意识到；实现", example: "I realize review matters.", level: "核心动词" },
  { word: "reason", phonetic: "/ˈriːzn/", meaning: "原因", example: "Find the reason for mistakes.", level: "核心名词" },
  { word: "receive", phonetic: "/rɪˈsiːv/", meaning: "收到", example: "Receive feedback quickly.", level: "核心动词" },
  { word: "remember", phonetic: "/rɪˈmembə/", meaning: "记住", example: "Remember words by examples.", level: "学习词" },
  { word: "review", phonetic: "/rɪˈvjuː/", meaning: "复习", example: "Review before forgetting.", level: "学习词" },
  { word: "sentence", phonetic: "/ˈsentəns/", meaning: "句子", example: "Make a sentence with it.", level: "学习词" },
  { word: "serious", phonetic: "/ˈsɪəriəs/", meaning: "严肃的；严重的", example: "Take spelling seriously.", level: "核心形容词" },
  { word: "similar", phonetic: "/ˈsɪmələ/", meaning: "相似的", example: "These two words are similar.", level: "阅读词" },
  { word: "situation", phonetic: "/ˌsɪtʃuˈeɪʃn/", meaning: "情况", example: "Understand the situation.", level: "阅读词" },
  { word: "solution", phonetic: "/səˈluːʃn/", meaning: "解决办法", example: "Review is the solution.", level: "抽象名词" },
  { word: "succeed", phonetic: "/səkˈsiːd/", meaning: "成功", example: "You can succeed.", level: "核心动词" },
  { word: "suggest", phonetic: "/səˈdʒest/", meaning: "建议", example: "I suggest daily review.", level: "核心动词" },
  { word: "support", phonetic: "/səˈpɔːt/", meaning: "支持", example: "Parents support learning.", level: "核心词" },
  { word: "through", phonetic: "/θruː/", meaning: "通过；穿过", example: "Learn through examples.", level: "高频介词" },
  { word: "understand", phonetic: "/ˌʌndəˈstænd/", meaning: "理解", example: "Understand before memorizing.", level: "核心动词" },
  { word: "valuable", phonetic: "/ˈvæljuəbl/", meaning: "有价值的", example: "Time is valuable.", level: "核心形容词" },
  { word: "without", phonetic: "/wɪˈðaʊt/", meaning: "没有", example: "Do not guess without review.", level: "高频介词" }
];
